---
- name: Check if user already exists
  servicenow.itsm.api_info:
    resource: sys_user
    sysparm_query: user_nameSTARTSWITH{{ snow_username }}
  register: requestresult

- name: Indicate user already exists a record is found
  ansible.builtin.debug:
    msg: "{{ snow_username }} already exists"
  when: requestresult.record | length  > 0

- name: Create ServiceNow User
  servicenow.itsm.api:
    resource: sys_user
    query_params:
      sysparm_input_display_value: true
    action: post
    data:
      user_name: "{{ snow_username }}"
      user_password: "{{ snow_password }}"
      first_name: "{{ first_name }}"
      last_name: "{{ last_name }}"
      department: IT
      email: "{{ snow_username }}@shadowman.dev"
      title: Shadowman
  register: user
  when: requestresult.record | length  == 0

- name: Attach role to new user
  servicenow.itsm.api:
    action: post
    resource: sys_user_has_role
    data:
      user: "{{ snow_username }}"
      role: admin
  when: requestresult.record | length  == 0
