---
- name: Create a change request in ServiceNow with Start Date
  servicenow.itsm.change_request:
    type: normal
    short_description: "{{ cr_short_description }}"
    description: "{{ owner | default('Shadowman') }} requests {{ cr_description }}"
    priority: high
    risk: moderate
    other:
      start_date: "{{ date_time | default(omit) }}"
      u_ritm: "{{ servicenow_ritm | default(omit) }}"
    impact: low
    assignment_group: CAB Approval
    state: assess
  register: request

- name: Send Approval e-mail
  community.general.mail:
    host: "{{ EMAIL_HOST }}"
    username: "{{ EMAIL_USERNAME }}"
    password: "{{ EMAIL_PASSWORD }}"
    port: "{{ EMAIL_PORT }}"
    subject: Approval request for ServiceNow Change Request {{ request.record.number }}
    body: "You have a new CR Approval request. Please click on this URL to approve: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=change_request.do?sysparm_query=number={{
      request.record.number }}"
    from: tower@shadowman.dev
    to: "{{ to_email }}"

- name: Pass along request information
  ansible.builtin.set_stats:
    data:
      request: "{{ request }}"
    per_host: false
